### ISSUE TITLE
Licensing: Upgrade to GPLv2+

### ISSUE THREAD

**Issue by ghost** [RinatKurmaev/Tether-companion#1]
You are using Android's support libraries, which are Apache2 licensed. However, these are considered incompatible with the plain GPLv2. A quick fix would be to add a section to the readme, that you make use of the "GPLv2 and later" clause..or just upgrade to gplv3.

**Comment by RinatKurmaev** [comment]
I have updated  license to gplv3.

**Comment by ghost** [comment]
Thanks for the quick response!
